services:

  mongodb:
    image: mongo:7
    container_name: cloudmasa-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: cloudmasa-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb

  server:
    image: vigneshkavi/cloudmasa-server:1.0
    container_name: cloudmasa-server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      # Database
      MONGO_URI: mongodb://admin:password123@mongodb:27017/cloudmasa?authSource=admin
      JWT_SECRET: supersecret123
      ENCRYPTION_KEY: 06711896bf90503706a9c925f898f7ca0851d98cb1cd82a8af307bdcf3bb4

      # Server
      PORT: 3000
      HOST: 0.0.0.0
      ENV: development
      FRONTEND_URL: http://localhost:5173

      # GitHub OAuth
      GITHUB_CLIENT_ID: Ov23lioFD7Uy9Px7zWI0
      GITHUB_CLIENT_SECRET: dac1b6a05c5aabfb0217d5fa180a71c29272d2b9
      GITHUB_AUTH_CALLBACK_URL: http://localhost:3000/github/callback

      # Google OAuth
      GOOGLE_CLIENT_ID: 855942551574-dqdl1s065hqlbn1em09ii1veh7uq2duc.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GOOGLE_AUTH_CALLBACK_URL: http://localhost:3000/api/auth/google/callback

      # Git token
      REACT_APP_GITTOKEN: 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

      # Email
      MAIL_SERVICE: gmail
      EMAIL_USER: cloudmasa.technology@gmail.com
      EMAIL_PASS: xuhvznfhhlyvzstg

      # Cloud
      ACCESS_KEY: f5609904-2040-4b35-b55b-0a64bde19663
      SECRET_KEY: Z7IinicGYSveLJD70mkTCvd82Q3MRvtof49X/aOBGow=

      # Support
      RESEND_API_KEY: re_NH2yKAdX_MKRdP4prPDyYxTrbKN8DPDUJ

  client:
    image: vigneshkavi/cloudmasa-client:1.0
    container_name: cloudmasa-client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongodb_data:
